# Default values for nfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: v1.0.8
  pullPolicy: IfNotPresent

nfs:
  hostPort: 2049

persistence:
  defaultClass: true
  hostPath: /srv
