apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: {{ .Release.Namespace }}
data:
  nodeLabelsForPV: |
    - kubernetes.io/hostname
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
